### ISSUE TITLE
Duplicate titles

### ISSUE THREAD

**Issue by unOmni** [lncrawl/lightnovel-crawler#1694]
Would love for the extra useless titles  to be removed so as to not have to use calibre or sigil to do it manually. a PC might be unavailable.

**Comment by idMysteries** [comment]
It should be easier with this. Give the name/link of the site.

**Comment by dipu-bd** [comment]
Create issue with the template. I already gave you the link to create issue in the discussion thread that you opened. Please check and read message. I am giving it again here: https://github.com/dipu-bd/lightnovel-crawler/issues/new?assignees=&labels=source-issue&template=3_source-issue.md&title=Fix+this+source
