### ISSUE TITLE
Readlightnovel.com problems

### ISSUE THREAD

**Issue by kalvinMB** [lncrawl/lightnovel-crawler#17]
I think there is a problem with readlightnovel.com 
the rest of the sites are okay. 
i Tried: book_crawler readln full-marks-hidden-marriage-pick-up-a-son-get-a-free-husband https://www.readlightnovel.org/full-marks-hidden-marriage-pick-up-a-son-get-a-free-husband/chapter-1830 https://www.readlightnovel.org/full-marks-hidden-marriage-pick-up-a-son-get-a-free-husband/chapter-1835

and this is what i get from terminal. 
Visiting  https://www.readlightnovel.org/full-marks-hidden-marriage-pick-up-a-son-get-a-free-husband
Getting book name and chapter list...
 [Full Marks Hidden Marriage: Pick Up a Son, Get a Free Husband] 1842 chapters found
Downloading https://www.readlightnovel.org/full-marks-hidden-marriage-pick-up-a-son-get-a-free-husband/chapter-1830
Downloading https://www.readlightnovel.org/full-marks-hidden-marriage-pick-up-a-son-get-a-free-husband/chapter-1831
Downloading https://www.readlightnovel.org/full-marks-hidden-marriage-pick-up-a-son-get-a-free-husband/chapter-1832
Downloading https://www.readlightnovel.org/full-marks-hidden-marriage-pick-up-a-son-get-a-free-husband/chapter-1833
Downloading https://www.readlightnovel.org/full-marks-hidden-marriage-pick-up-a-son-get-a-free-husband/chapter-1834
Saving  Full Marks Hidden Marriage Pick Up a Son, Get a Free Husband/json/19/01836.json
Saving  Full Marks Hidden Marriage Pick Up a Son, Get a Free Husband/json/19/01835.json
Downloading https://www.readlightnovel.org/full-marks-hidden-marriage-pick-up-a-son-get-a-free-husband/chapter-1835
Downloading https://www.readlightnovel.org/full-marks-hidden-marriage-pick-up-a-son-get-a-free-husband/chapter-1841
Saving  Full Marks Hidden Marriage Pick Up a Son, Get a Free Husband/json/19/01834.json
Saving  Full Marks Hidden Marriage Pick Up a Son, Get a Free Husband/json/19/01837.json
Saving  Full Marks Hidden Marriage Pick Up a Son, Get a Free Husband/json/19/01833.json
Saving  Full Marks Hidden Marriage Pick Up a Son, Get a Free Husband/json/19/01838.json
Saving  Full Marks Hidden Marriage Pick Up a Son, Get a Free Husband/json/19/01839.json
complete
Processing: Full Marks Hidden Marriage Pick Up a Son, Get a Free Husband/json/19
Creating: Full Marks Hidden Marriage Pick Up a Son, Get a Free Husband/epub/Full Marks Hidden Marriage: Pick Up a Son, Get a Free Husband_v19.epub
Traceback (most recent call last):
  File "/anaconda3/lib/python3.5/site-packages/ebook_crawler/binding.py", line 128, in novel_to_mobi
    generator(KINDLEGEN_PATH_MAC)
  File "/anaconda3/lib/python3.5/site-packages/ebook_crawler/binding.py", line 123, in <lambda>
    generator = lambda kindlegen: call([kindlegen, epub_file])
  File "/anaconda3/lib/python3.5/subprocess.py", line 247, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/anaconda3/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/anaconda3/lib/python3.5/subprocess.py", line 1289, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.5/site-packages/ebook_crawler/binding.py", line 136, in novel_to_mobi
    generator('kindlegen')
  File "/anaconda3/lib/python3.5/site-packages/ebook_crawler/binding.py", line 123, in <lambda>
    generator = lambda kindlegen: call([kindlegen, epub_file])
  File "/anaconda3/lib/python3.5/subprocess.py", line 247, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/anaconda3/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/anaconda3/lib/python3.5/subprocess.py", line 1289, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'kindlegen'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/bin/ebook_crawler", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.5/site-packages/ebook_crawler/__init__.py", line 51, in main
    volume=volume,
  File "/anaconda3/lib/python3.5/site-packages/ebook_crawler/readln.py", line 49, in start
    novel_to_mobi(self.output_path)
  File "/anaconda3/lib/python3.5/site-packages/ebook_crawler/binding.py", line 138, in novel_to_mobi
    if err[1].errno == errno.ENOENT:
TypeError: 'FileNotFoundError' object is not subscriptable

after the result i get is only an epub with all the titles with no content.

**Comment by yudilee** [comment]
There is inconsistency in web structure that make web scrapper code not work. may need some time to analyze it. I have some suggestion how about using another source 

book_crawler wuxiac Hidden-Marriage https://www.wuxiaworld.co/Hidden-Marriage/1201253.html https://www.wuxiaworld.co/Hidden-Marriage/1202033.html. 

As far as i know for novel which come from webnovel.com you can get novel that has been paywalled for free from this source (wuxiaworld.co).
