### ISSUE TITLE
Fix https://novelbin.com

### ISSUE THREAD

**Issue by JoahTremblay** [lncrawl/lightnovel-crawler#2201]
**Novel URL**:     <your novel url or query>https://novelbin.com/novelbin/a-practical-guide-to-evil
**App Location**:    PIP
**App Version**:   3.4.0  

## Describe this issue
I have encountered a rate limit issue with NovelBin and its copies.

To fix this, I modified the utils/ratelimit.py file in my locally by changing the line "self.period = 1 / ratelimit" to "self.period = 2 / ratelimit".

I recommend adjusting this setting specifically for NovelBin to ensure a more accurate rate limit.

Thank you for your time.

**Comment by zGadli** [comment]
It gives a 403 Client Error: Forbidden for URL: https://novelbin.com/novelbin/a-practical-guide-to-evil . It might be Cloudfare blocking access.

**Comment by JoahTremblay** [comment]
Closed for being stale
