### ISSUE TITLE
https://www.chereads.com

### ISSUE THREAD

**Issue by mmikail07** [lncrawl/lightnovel-crawler#2414]
- Language: English
- Supports Searching: Yes
- Contains Machine Translations: No
- Contains Manga/Manhua/Manhwa: No
- Has CloudFlare Protection: Not sure

**Comment by camp00000** [comment]
This seems quite unnecessary to add as you could at most, download maybe 10-15 chapters of any given novel as
the website seems to have its own app which is forced upon anyone trying to read further in than that.

See
![image](https://github.com/user-attachments/assets/d7ea1e85-6df6-44fc-8401-4babaee4a5a4)
App: https://play.google.com/store/apps/details?id=com.chereads.reader&hl=en_US


Unless there are any novels that are fully available on their website, not app, please close this issue @mmikail07 .
